# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaymentApp' do
  use_frameworks!
  
  pod 'Alamofire' , '~> 4.7.3'
  pod 'ObjectMapper'
  pod 'Firebase'
  pod 'Kingfisher'
  pod 'TinyConstraints'
  pod 'lottie-ios' , '~> 2.0.3'

end
